version: '3'

services:
        jenkinsci-byznass:
                build: .
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ./jenkins-data:/var/jenkins_home
                ports:
                        - "50000:50000"
                user: "${UID}:${GID}"
        nginx-proxy:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - ./certs/:/etc/ssl/jenkins
                ports:
                        - "80:80"
                        - "443:443"
