version: '3'

services:
        jenkinsci-byznass:
                build: .
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - jenkins-data:/var/jenkins_home
                user: "jenkins:${DOCKER_GID}"
                environment:
                        - DB_INTEGRATION_TEST_HOST=dbIntegrationTestPostgresContainer
                networks:
                        - dbIntegrationTest
                        - jenkinsCiNetwork
        nginx-proxy:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - ./certs/:/etc/ssl/jenkins
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - jenkinsCiNetwork
        postgres-byznass:
                image: postgres
                environment:
                        - POSTGRES_USER=sonar
                        - POSTGRES_PASSWORD=sonar
                volumes:
                        - postgres-data:/var/lib/postgresql/data
                networks:
                        - jenkinsCiNetwork
        sonarqube-byznass:
                image: sonarqube:6.7-community
                volumes:
                        - sonarqube-data-conf:/opt/sonarqube/conf
                        - sonarqube-data-data:/opt/sonarqube/data
                        - sonarqube-data-logs:/opt/sonarqube/logs
                        - sonarqube-data-extensions:/opt/sonarqube/extensions
                environment:
                        - sonar.jdbc.username=sonar
                        - sonar.jdbc.password=sonar
                        - sonar.jdbc.url=jdbc:postgresql://postgres-byznass/sonar
                networks:
                        - jenkinsCiNetwork

volumes:
        jenkins-data:
        postgres-data:
        sonarqube-data-conf:
        sonarqube-data-data:
        sonarqube-data-logs:
        sonarqube-data-extensions:

networks:
        dbIntegrationTest:
                name: dbIntegrationTest
                driver: bridge
        jenkinsCiNetwork:
                name: jenkinsCiNetwork
                driver: bridge
